### ISSUE TITLE
Why there is a need t concvert Pytorch model to some other for making it run on Raspberry Pi?

### ISSUE THREAD

**Issue by jaskiratsingh2000** [BlueMirrors/cvu#20]
@shivamswarnkar I just have a question that what is the core difference between the Pytorch Model and the Exported(Tflite model)? As I could see that Pytorch model is not working well on the Raspberry Pi whereas the Tflite works better but I am not able to figure out at what are the reasons for that it's working.

What does the Pytorch model do that Tflite doesn't do?

@shivamswarnkar Do you have any idea about that?

**Comment by shivamswarnkar** [comment]
Hi, 

There isn't any difference in pytorch and tflite model, they might have different precision because of weights conversion but model architecture is same. In our CVU test, pytorch and tflite had almost identical results.

**Comment by jaskiratsingh2000** [comment]
I was getting no inferences with Pytorch model on RPI whereas I was getting
inferences with tflite model. I am not able to understand why.

Is architecture same? Can you try explaining ne what exactly it is?

**Comment by jaskiratsingh2000** [comment]
@shivamswarnkar

**Comment by shivamswarnkar** [comment]
@jaskiratsingh2000 Architecture is same. Only difference is of framework. 

Have you tried to run inference with CVU? If you don't get detection with cvu with pytorch backend then I can try to debug your issue.
