### ISSUE TITLE
What is inside the Pytorch model of YOLOv5

### ISSUE THREAD

**Issue by jaskiratsingh2000** [BlueMirrors/cvu#21]
Hi  @shivamswarnkar I just have a quick question to understand regarding which I am having a hard time understanding it since long. What is actually inside the Pytorch model and Tflite model? I don't understand that what's the format inside the PyTorch model. When do we say that we are compiling the Pytorh model then what does happen intermediately?

**Comment by shivamswarnkar** [comment]
duplicate issue of https://github.com/BlueMirrors/cvu/issues/20
