### ISSUE TITLE
failed benchmark on jetson nano

### ISSUE THREAD

**Issue by chunxiao3600** [BlueMirrors/cvu#31]
jetson installed jetpack 5.0.1 ,I have installed all required packages .I use below command to test:
`sudo python3 benchmark.py -backend  onnx torch tflite -video 0 -device cpu`
but report errors:
`
[CVU-Info] Backend: Onnx-1.11.1-cpu
[ WARN:0@35.326] global /io/opencv/modules/videoio/src/cap_v4l.cpp (1927) getProperty VIDEOIO(V4L2:/dev/video0): Unable to get camera FPS
Traceback (most recent call last):
  File "benchmark.py", line 238, in <module>
    test_video(OPT.backend, OPT.video, OPT.max_frames, OPT.warmups,
  File "benchmark.py", line 144, in test_video
    writer = vidsz.Writer(reader,
  File "/usr/local/lib/python3.8/dist-packages/vidsz/opencv/writer/base_writer.py", line 62, in __init__
    raise AssertionError(
AssertionError: Failed to Create Writer for the given settings.`

How to fix?
thank you

**Comment by shivamswarnkar** [comment]
Hi @chunxiao3600 looks like the writer is failing to get the camera's FPS. This could mean that reader is failing to connect to your webcam or your webcam does not provide fps info. 

You could do any one of the following
- manually provide some `fps` value here [Line#139](https://github.com/BlueMirrors/cvu/blob/4605adbeebf79f0df7484b4e88537d4fa91463b9/examples/benchmark.py#L139)
-  use `-no-write` to avoid creating a video, or 
- remove `-video` flag and it'll download an example video to benchmark for testing

For reference, you can set these arguments for the writer [Implementation-Link](https://github.com/BlueMirrors/vidsz/blob/8e99d5a7e89ca21b114058a413b252f51f824f0f/vidsz/opencv/writer/base_writer.py#L20)

Feel free to reopen this issue if you still face problems. Thanks.

**Comment by chunxiao3600** [comment]
I have used "python3 benchmark.py -backend onnx -device cpu" successfully.
but  failed with "python3 benchmark.py -backend onnx -device gpu" .
My device is jetson nano, detail below:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_11_23:44:05_PST_2021
Cuda compilation tools, release 11.4, V11.4.166
Build cuda_11.4.r11.4/compiler.30645359_0`
I want to benchmark gpu cuda performance ,but don't how to do .
thanks

**Comment by chunxiao3600** [comment]
> Hi @chunxiao3600 looks like the writer is failing to get the camera's FPS. This could mean that reader is failing to connect to your webcam or your webcam does not provide fps info.
> 
> You could do any one of the following
> 
> * manually provide some `fps` value here [Line#139](https://github.com/BlueMirrors/cvu/blob/4605adbeebf79f0df7484b4e88537d4fa91463b9/examples/benchmark.py#L139)
> * use `-no-write` to avoid creating a video, or
> * remove `-video` flag and it'll download an example video to benchmark for testing
> 
> For reference, you can set these arguments for the writer [Implementation-Link](https://github.com/BlueMirrors/vidsz/blob/8e99d5a7e89ca21b114058a413b252f51f824f0f/vidsz/opencv/writer/base_writer.py#L20)
> 
> Feel free to reopen this issue if you still face problems. Thanks.

please reopen this issue

**Comment by shivamswarnkar** [comment]
@chunxiao3600 can you please create a new issue for the `GPU` testing? 

Also, can you please provide the error log you're getting when testing `onnx-gpu`?
