### ISSUE TITLE
failed benchmark on jetson nano with onnx model 

### ISSUE THREAD

**Issue by chunxiao3600** [BlueMirrors/cvu#32]
I used "python3 benchmark.py -video people.mp4 -backend onnx -device cuda",error below:
```
root@ubuntu:/home/yolo/yolov5# python3 benchmark.py -video people.mp4 -backend onnx -device cuda


[CVU-Info] Backend: Onnx-1.11.0-cuda
Traceback (most recent call last):
  File "benchmark.py", line 238, in <module>
    test_video(OPT.backend, OPT.video, OPT.max_frames, OPT.warmups,
  File "benchmark.py", line 141, in test_video
    detector = Detector(classes='coco', backend=backend, device=device)
  File "/usr/local/lib/python3.8/dist-packages/cvu/detector/yolov5/core.py", line 78, in __init__
    self._load_model(backend, weight, device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cvu/detector/yolov5/core.py", line 169, in _load_model
    self._model = backend.Yolov5(weight, device)
  File "/usr/local/lib/python3.8/dist-packages/cvu/detector/yolov5/backends/yolov5_onnx.py", line 45, in __init__
    self._load_model(weight)
  File "/usr/local/lib/python3.8/dist-packages/cvu/detector/yolov5/backends/yolov5_onnx.py", line 73, in _load_model
    self._model = onnxruntime.InferenceSession(weight, None)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 363, in _create_inference_session
    raise ValueError("This ORT build has {} enabled. ".format(available_providers) +
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
```

ENV info:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_11_23:44:05_PST_2021
Cuda compilation tools, release 11.4, V11.4.166
Build cuda_11.4.r11.4/compiler.30645359_0
```
I used docker image is :nvcr.io/nvidia/l4t-pytorch

**Comment by shivamswarnkar** [comment]
Hi @chunxiao3600 this is a known issue with newer versions of ONNX. We have a fix in review with #24 

Run following to try out the latest changes (it's a dev branch, still in review)
`git checkout fix-package-utils`

And use `device -gpu` in `benchmark`

**Comment by chunxiao3600** [comment]
I have checked out :**git clone -b fix-package-utils https://github.com/BlueMirrors/cvu.git**
And cd cvu/examples ,run:**python3 benchmark.py -video people.mp4 -backend onnx -device cuda**
still have error

**Comment by shivamswarnkar** [comment]
Is it the same error or different? Can you post the logs again?

**Comment by chunxiao3600** [comment]
same error .

**Comment by shivamswarnkar** [comment]
@chunxiao3600  you shouldn't get the same error. Did you pip install `cvu` before? 

Also, I think if you `cd` into `examples` then it probably won't be able to read local `cvu`

Try this

`PYTHONPATH=./ python examples/benchmark.py -backend onnx -device gpu`

Add whatever error log you get here with this command.

**Comment by chunxiao3600** [comment]
error below:
```
**root@ubuntu:/home/yolo/cvu# PYTHONPATH=./ python3 examples/benchmark.py -backend onnx -device gpu**
Traceback (most recent call last):
  File "examples/benchmark.py", line 13, in <module>
    from cvu.utils.backend.package import setup
ImportError: cannot import name 'setup' from 'cvu.utils.backend.package' (/home/yolo/cvu/./cvu/utils/backend/package.py)
**root@ubuntu:/home/yolo/cvu# pip list |grep cvu**
cvu-python              0.0.1a1
```

**Comment by shivamswarnkar** [comment]
Yeah, just replace `line 13` in `examples/benchmark.py` with below (this is a temp fix, I'm pushing a real fix soon)


`from cvu.utils.backend.package import setup_package as setup`

This should make it work

**Comment by shivamswarnkar** [comment]
I have pushed the changes as well, you can just do a `git pull` and it should work

**Comment by chunxiao3600** [comment]
[CVU-Error] Vidsz Import Failed, either change backend or reinstall it properly...
2022-07-13 11:13:58.976437129 [E:onnxruntime:Default, provider_bridge_ort.cc:1022 Get] Failed to load library libonnxruntime_providers_cuda.so with error: libcublas.so.10: cannot open shared object file: No such file or directory
2022-07-13 11:13:58.976535497 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:552 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
 FPS(onnx): 2.531
 Video saved at: temp/people_onnx.mp4
 FPS(onnx): 2.531

**Comment by shivamswarnkar** [comment]
Looks like your ONNX is failing to use CUDA properly, which means it's either not properly linked or has some version mismatch. I have tested the latest changes on multiple devices, and it's working as expected. So the issue is probably with your configuration. 

Can you try to run the tensorRT backend? 

`python3 examples/benchmark.py -backend tensorrt -device gpu`


If `TensorRT` backend works properly, then try replacing `'CUDAExecutionProvider'` with `'TensorrtExecutionProvider'`  in below line, and run `Onnx-backend` again https://github.com/BlueMirrors/cvu/blob/65ab59821f8b30ff9120adc157e4025b47dc1020/cvu/detector/yolov5/backends/yolov5_onnx.py#L75

**Comment by chunxiao3600** [comment]
this command run successfully . `python3 examples/benchmark.py -backend tensorrt -device gpu`
benchmark result is up to 14fps.
I tried replacing 'CUDAExecutionProvider' with 'TensorrtExecutionProvider' in 
`[cvu/cvu/detector/yolov5/backends/yolov5_onnx.py](https://github.com/BlueMirrors/cvu/blob/65ab59821f8b30ff9120adc157e4025b47dc1020/cvu/detector/yolov5/backends/yolov5_onnx.py#L75)`
still only have 2 fps .
I noticed an error :
`2022-07-14 05:22:54.490336277 [E:onnxruntime:Default, provider_bridge_ort.cc:1022 Get] Failed to load library libonnxruntime_providers_tensorrt.so with error: libcudart.so.10.2: cannot open shared object file: No such file or directory`

My docker is :https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml with **tag**
r34.1.1-py3
It looks have installed onnx package.

**Comment by chunxiao3600** [comment]
thank you very much .
